<a href="https://colab.research.google.com/github/sandeep1847e/pytorch-1/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
3*3

9

In [8]:
import torch
import numpy as np

In [2]:
# !pip list

In [1]:
list1 = [[1,2,1,2,1],[2,3,2,3,2]]
list1

[[1, 2, 1, 2, 1], [2, 3, 2, 3, 2]]

**Tensors**

In [6]:
tensor2 = torch.randn(2,4)
tensor2

tensor([[ 0.4570,  1.4104, -0.6084, -0.5779],
        [-1.3672,  0.4459, -0.8948,  0.9578]])

**tensors and numpy conversion**

In [9]:
np1=np.random.randn(2,4)
np1

array([[ 0.29659575, -0.21598138, -0.86634932,  0.53094284],
       [ 1.19342102, -0.31025257, -0.61305796, -0.72071531]])

In [10]:
np1.dtype

dtype('float64')

In [11]:
np2torch = torch.tensor(np1)
np2torch

tensor([[ 0.2966, -0.2160, -0.8663,  0.5309],
        [ 1.1934, -0.3103, -0.6131, -0.7207]], dtype=torch.float64)