<a href="https://colab.research.google.com/github/sandeep1847e/pytorch-1/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
3*3

9

In [8]:
import torch
import numpy as np

In [2]:
# !pip list

In [1]:
list1 = [[1,2,1,2,1],[2,3,2,3,2]]
list1

[[1, 2, 1, 2, 1], [2, 3, 2, 3, 2]]

**Tensors**

In [6]:
tensor2 = torch.randn(2,4)
tensor2

tensor([[ 0.4570,  1.4104, -0.6084, -0.5779],
        [-1.3672,  0.4459, -0.8948,  0.9578]])

**tensors and numpy conversion**

In [13]:
np1=np.random.randn(3,4)
np1

array([[ 0.09611371, -0.18441425, -0.2893769 , -0.73516417],
       [ 1.0849576 ,  1.1897445 , -0.13273666,  0.81173974],
       [-0.02587737, -1.30623085, -0.12805644, -0.66656931]])

In [14]:
np1.dtype

dtype('float64')

In [15]:
np2torch = torch.tensor(np1)
np2torch

tensor([[ 0.0961, -0.1844, -0.2894, -0.7352],
        [ 1.0850,  1.1897, -0.1327,  0.8117],
        [-0.0259, -1.3062, -0.1281, -0.6666]], dtype=torch.float64)

# **reshaping tensors!**

In [17]:
np2torch.reshape(2,6)

tensor([[ 0.0961, -0.1844, -0.2894, -0.7352,  1.0850,  1.1897],
        [-0.1327,  0.8117, -0.0259, -1.3062, -0.1281, -0.6666]],
       dtype=torch.float64)

# Note : reshape and view update the dimensions!



# Math operations!